### ISSUE TITLE
stuck local images

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/ios#3] opened 2016-08-08 01:10 UTC
See https://twitter.com/kevin_bullock/status/762082566526504960

What can we do about this?

**Comment by bogdans-telenav** [comment] 2016-08-08 08:56
Have to say this is the first time that i hear about this case.

Before doing anything, in order to find out more about this problem, can we ask for iOS version and device model? And a simple task just make another small trip to see if the problem persists.

If the problem persists then i will need some files from the device to see what is the problem. In order to do this: 
        1. Open iTunes with your iPhone connected to your computer using the USB cable.
        2. Select your device in iTunes. 
        3. In the left sidebar, click Apps. All the apps that you have on your device should appear on the right side. 
        4. On the right side, scroll down until you see File Sharing and select OSV.
        5. Copy all files and folders from OSV to your computer. (Should be 6 in total: default.realm, default.realm.lock, default.realm.management, default.realm.note, OSVLogs, Photos)
        6. Send us a link to download this files and folders. 

-Workaround to upload-
The simplest workaround is to follow steps 1 to 5 and use the upload script or upload tool.

**Comment by martijnv-telenav** [comment] 2016-08-10 22:17
Asked OP to comment here.

**Comment by kevinbullock** [comment] 2016-08-10 22:56
Hi, thanks for creating this ticket @martijnv-telenav.

Device is iPhone6 model MG5W2LL/A
iOS version 9.3.3 (however I just installed 9.3.4)

To remedy this issue, I uninstalled OSV and reinstalled. This appears to have solved the problem. I have done 2 small drives since then and have watched the filesize grow (post drive) and shrink (post upload). I will try a longer drive and test to make sure it is still working optimally. 

Kevin

**Comment by bogdans-telenav** [comment] 2016-08-11 07:43
@kevinbullock thanks for your response.

I am using the same model, and did not managed to reproduce. If this problem persists please send me the data.

For future usage god to know before uninstalling:
If you did not manage to upload your data and/or your app for some reason can not upload your data, save it on your computer using my previous answer and use the upload scripts or upload tool to upload. This way you don't loose anything.

I will close this. If you can still reproduce this issue please reopen.

**Closed as completed** 2016-08-11 07:49 UTC
Labels: bug
