### ISSUE TITLE
Uploads not being processed

### ISSUE THREAD

**Issue by theid** [openstreetcam/ios#27] opened 2017-03-24 22:13 UTC
Several of my uploads have been disappearing. Today 3 of 5 recordings were lost in one go. The app uploads, the data is deleted from the phone (iPhone 7) and no error is reported. Application does not crash and there is no error log. It appears the server eats them. It is quite frustrating because as you know it takes time, effort, and money to drive around doing this!

I will be happy to assist, however I do not have an Xcode development machine at hand. My OSM account is theid.

**Comment by theid** [comment] 2017-04-05 22:04
As an example, the highlighted below was not processed on upload...
<br>
![img_1907](https://cloud.githubusercontent.com/assets/4463936/24728644/b3dca394-1a52-11e7-99fa-0ebe2db411fb.jpg)

The other three can be seen post processing on the website:

![uploaded_series](https://cloud.githubusercontent.com/assets/4463936/24728760/30df6926-1a53-11e7-8ae6-d802e127ef8a.png)

**Comment by theid** [comment] 2017-04-05 22:47
[05-04-2017 17_46.log.txt](https://github.com/openstreetcam/ios/files/900982/05-04-2017.17_46.log.txt)

**Comment by bogdans-telenav** [comment] 2017-05-05 14:30
@theid  First let me appreciate your report, we almost never (you are the first) get a report as good as yours. About your issue: as i could tell form your log file the iOS application did its job, but the server side did not process every recording that you uploaded. 
Current status on server: we are actually reimplementing the processing part (because there are several bugs that ware found here). My guess is that your "missing" recordings are on the server but they are stuck in a processing queue. I will talk with the guy working on this to try to find your recordings. I can not promise that you will get them back, but I must say that until know we did not experienced any recoding loss so it is fair to assume that you will get them back.

**Comment by bogdans-telenav** [comment] 2017-05-09 09:20
@theid I can confirm that your recordings are on the server. There was a bug on the processing part, your tracks stuck in a processing state. After we make them visible i will close this.

**Comment by bogdans-telenav** [comment] 2017-12-04 10:07
This was fixed in the meantime.

**Closed as completed by bogdans-telenav** 2017-12-04 10:07 UTC
Labels: bug
