### ISSUE TITLE
Corrupted images being captured

### ISSUE THREAD

**Issue by hoylen** [openstreetcam/ios#24] opened 2016-10-07 01:59 UTC
The image/video gets corrupted during a capture, with the entire picture filled with just video noise (i.e. no recognisable picture in it).

This has happened to me twice with OSV version 1.4.3(1) running on an iPhone 5s. On both occasions, it has happened after capturing for a long time (over 30 minutes).

See the last frames of this tracks: http://www.openstreetview.org/details/23871/1374

This may or may not be related, but in the previous release of the app before version 1.4.3(1), I've seen it start put a feint ghost-copy of another part of the image on it. See the end of this track, where the ghost-part is from another section of the image (it is not a reflection on the windscreen): http://www.openstreetview.org/details/22230/8055

In both cases, the noise/distortion was seen both on the iPhone screen and in the captured images. The capture was stopped, and the problem didn't appear when starting a new capture.

**Comment by bogdans-telenav** [comment] 2016-10-07 12:44
@hoylen Thanks for reporting this. This is the first time we find out about it, we will investigate more, and replay when we have more info on this.

**Comment by bogdans-telenav** [comment] 2017-05-05 14:40
@hoylen did you ever reproduce this on the latest version? My personal opinion is that this bug was caused by our server side. The server generates photos from the video file that we write on your device, this photos got corrupted on generation. I will talk with our server guy to reprocess your tracks. In the mean time we made some improvements on the client side to so please recheck. I will close this issue after your recording will be reprocessed.

**Comment by hoylen** [comment] 2017-05-05 22:06
No, I couldn't reproduce the problem.

But if it is cause by a server-side bug, the evidence should be obvious: the photos contains the noise, but the source video will be clean.

I'm happy for you to close this ticket.

**Comment by bogdans-telenav** [comment] 2017-05-08 09:43
We checked it was a client bug (the video was corrupted)

**Closed as completed by bogdans-telenav** 2017-05-08 09:43 UTC
Labels: bug
